spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/postgres_globus
    username: globus
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true